import { User } from "./types";

const mockData: User[] = [
  {
    id: "1",
    firstName: "John",
    lastName: "Doe",
    email: "john.doe@michalwarchol.com",
    role: "admin",
    avatar: "https://i.pravatar.cc/150?img=11",
    createdAt: "2021-01-01",
    updatedAt: "2021-01-01",
  },
  {
    id: "2",
    firstName: "Jane",
    lastName: "Smith",
    email: "jane.smith@michalwarchol.com",
    role: "user",
    avatar: "https://i.pravatar.cc/150?img=12",
    createdAt: "2021-01-01",
    updatedAt: "2021-01-01",
  },
  {
    id: "3",
    firstName: "Alex",
    lastName: "Nowak",
    email: "alex.nowak@michalwarchol.com",
    role: "user",
    avatar: "https://i.pravatar.cc/150?img=13",
    createdAt: "2021-02-11",
    updatedAt: "2021-02-11",
  },
  {
    id: "4",
    firstName: "Maria",
    lastName: "Garcia",
    email: "maria.garcia@michalwarchol.com",
    role: "admin",
    avatar: "https://i.pravatar.cc/150?img=14",
    createdAt: "2021-03-04",
    updatedAt: "2021-03-04",
  },
  {
    id: "5",
    firstName: "Tom",
    lastName: "Brown",
    email: "tom.brown@michalwarchol.com",
    role: "user",
    avatar: "https://i.pravatar.cc/150?img=15",
    createdAt: "2021-05-19",
    updatedAt: "2021-05-19",
  },
  {
    id: "6",
    firstName: "Emma",
    lastName: "Wilson",
    email: "emma.wilson@michalwarchol.com",
    role: "user",
    avatar: "https://i.pravatar.cc/150?img=16",
    createdAt: "2021-07-23",
    updatedAt: "2021-07-23",
  },
  {
    id: "7",
    firstName: "Lucas",
    lastName: "Kowalski",
    email: "lucas.kowalski@michalwarchol.com",
    role: "user",
    avatar: "https://i.pravatar.cc/150?img=17",
    createdAt: "2021-09-08",
    updatedAt: "2021-09-08",
  },
  {
    id: "8",
    firstName: "Olivia",
    lastName: "Taylor",
    email: "olivia.taylor@michalwarchol.com",
    role: "admin",
    avatar: "https://i.pravatar.cc/150?img=18",
    createdAt: "2021-11-30",
    updatedAt: "2021-11-30",
  },
  {
    id: "9",
    firstName: "Noah",
    lastName: "Anderson",
    email: "noah.anderson@michalwarchol.com",
    role: "user",
    avatar: "https://i.pravatar.cc/150?img=19",
    createdAt: "2022-01-17",
    updatedAt: "2022-01-17",
  },
  {
    id: "10",
    firstName: "Sophia",
    lastName: "Martinez",
    email: "sophia.martinez@michalwarchol.com",
    role: "user",
    avatar: "https://i.pravatar.cc/150?img=20",
    createdAt: "2022-04-05",
    updatedAt: "2022-04-05",
  },
  {
    id: "11",
    firstName: "Ethan",
    lastName: "Lewandowski",
    email: "ethan.lewandowski@michalwarchol.com",
    role: "user",
    avatar: "https://i.pravatar.cc/150?img=21",
    createdAt: "2022-06-21",
    updatedAt: "2022-06-21",
  },
  {
    id: "12",
    firstName: "Jan",
    lastName: "Kowalczyk",
    email: "jan.kowalczyk@michalwarchol.com",
    role: "user",
    avatar: "https://i.pravatar.cc/150?img=22",
    createdAt: "2022-08-14",
    updatedAt: "2022-08-14",
  },
];

export default mockData;
